services:
  - type: web
    name: people-counter-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: storage
      mountPath: /app/static
      sizeGB: 5
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
